### ISSUE TITLE
How can I ignore a story?

### ISSUE THREAD

**Issue by Auroratide** [compoze-labs/storyshots#1]
Maybe there's a story that's currently flakey and I want to ignore it in the meantime while it is fixed. Is there a way to exclude the story from storyshot's automation?

**Comment by adameichelkraut** [comment]
You should now be able to ignore stories via a configuration file `.storyshots.config.json` and add the following:
```json
{
    "ignoreStories": [
        "your-story--to-ignore"
    ]   
}
```

See the README.md for more details! :)
