### ISSUE TITLE
Exceeded Timeout after running less than 10 stories

### ISSUE THREAD

**Issue by Auroratide** [compoze-labs/storyshots#6]
It looks like the timeout is hardcoded to 10 seconds, and already for 10 stories this isn't enough.

I can see two options here:

1. We make the timeout configurable so the user can determine how much time they need.
2. We somehow run the tests in parallel so that _each_ test has a 10-second timeout. Maybe this will also speed up execution time of the tests.

```
1) [chromium] › storyshots.testStories.ts:8:9 › visual regressions › specs =======================

    Test timeout of 10000ms exceeded.

    page.goto: net::ERR_ABORTED; maybe frame was detached?
```

**Comment by adameichelkraut** [comment]
ahh also increased timeout to 5min after seeing it reproduce too.

see commit https://github.com/compoze-labs/storyshots/commit/8969bc64e476e03080ba4cf2af33b55b556286b8
